version: '2'

services:
  transactions-db:
    image: 'postgres:14.3-alpine'
    restart: always
    container_name: transactions-db
    environment:
      - POSTGRES_USER=plutus
      - POSTGRES_PASSWORD=plutuspass
      - POSTGRES_DB=transactions-db
    ports:
      - "5432:5432"
